
build:
  stage : build
  image: python:latest
  script:
    - python -m py_compile src/fizzbuzz/*

tests:
  stage: tests
  image: python:latest
  script:
    - pip install tox
    - tox -c ./src/tox.ini

pages:
  stage : pages
  image: ruby
  script:
  - gem install compass zurb-foundation # CSS stylesheets generation
  - gem install prawn -v 2.1.0
  - gem install asciidoctor # HTML generation
  - gem install asciidoctor-pdf # HTML generation

  - asciidoctor src/doc/documentation.adoc -o public/index.html
  - asciidoctor-pdf src/doc/documentation.adoc -o public/documentation.pdf

  artifacts:
    paths:
    - public

  only:
  - master

stages:
  - build
  - tests
  - pages