image: ruby

pages:
  script:
  - gem install compass zurb-foundation # CSS stylesheets generation
  - gem install prawn -v 2.1.0
  - gem install asciidoctor # HTML generation
  - gem install asciidoctor-pdf # HTML generation

  - asciidoctor src/mon_best_seller.adoc -o public/index.html
  - asciidoctor-pdf src/mon_best_seller.adoc -o public/mon_best_seller.pdf

  artifacts:
    paths:
    - public

  only:
  - master