image: python:latest


build:
  stage : build
  script:
    - python -m py_compile src/fizzbuzz/*

tests:
  stage: tests
  script:
    - pip install tox
    - tox -c ./src/tox.ini

stages:
  - build
  - tests

# pages:
#   script:
#   - gem install compass zurb-foundation # CSS stylesheets generation
#   - gem install prawn -v 2.1.0
#   - gem install asciidoctor # HTML generation
#   - gem install asciidoctor-pdf # HTML generation

#   - asciidoctor src/mon_best_seller.adoc -o public/index.html
#   - asciidoctor-pdf src/mon_best_seller.adoc -o public/mon_best_seller.pdf

#   artifacts:
#     paths:
#     - public

#   only:
#   - master